[project]
name = "migratable-aws-stacker"
version = "0.1.0"
description = "Provides a stacker project which can be used to test migrations to other infrastructure-as-code frameworks and languages."
authors = [{ name = "Kevin Brockhoff", email = "kbrockhoff@codekaizen.org" }]

[tool.poetry]
name = "migratable-aws-stacker"
version = "0.1.0"
description = ""
authors = []
packages = [
    { include = "migratable_aws_stacker" }
]

[tool.poetry.dependencies]
python = "^3.9"
stacker_blueprints = "^1.0.8"
aws-cdk-lib = "^2.0.0"
constructs = "^10.0.0"

[tool.poetry.group.dev.dependencies]
nose = "^1.3"
mock = "^2.0"
flake8 = "^3.5"
setuptools = "^69.0.0"
pytest = "^8.0.0"

[project.optional-dependencies]
test = [
  "pytest"
]
