[project]
name = "migratable-aws-stacker"
version = "0.1.0"
description = "Provides a stacker project which can be used to test migrations to other infrastructure-as-code frameworks and languages."
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [
  { name = "Kevin Brockhoff", email = "kbrockhoff@codekaizen.org" }
]
requires-python = ">=3.9,<3.10"
packages = [
    { include = "migratable_aws_stacker" }
]
dependencies = [
    "stacker>=1.7.2",
    "stacker_blueprints>=1.0.8",
    "boto3>=1.26.0",
    "troposphere>=4.0.0",
    "aws-cdk-lib>=2.0.0",
    "constructs>=10.0.0",
]

[project.optional-dependencies]
test = [
  "pytest>=8.0.0"
]
